### ISSUE TITLE
Module #10 - Legal and Policy Issues

### ISSUE THREAD

**Issue by dbloom** [DataONEorg/dataone_lessons#15]
I have begun the process of moving this module (formerly #11) into dataone_lessons.  If anyone decided to add to this module, please let me know first.
- [x] Transfer all text content to the slides
- [x] Compare text transferred to most recent ppt - ensure it's current
- [x] Re-export images - rework images to ensure high quality graphics in the presentation
- [x] Check notes - ensure all notes that aren't a duplicate of the slide content are transferred.
- [ ] Update styling (Columns, image sizes, font size and color, etc.)

**Comment by dbloom** [comment]
Slides are all loaded and merged.

CSS tweaks for image sizing, centering in columns, and font size and color for attributions, (re: #26 and #24 ) are up next when everything is ready.

**Comment by aebudden** [comment]
All slides have been reviewed / edited / cleaned.  There are a few minor items remaining but I will migrate into a single issues thread.
