### ISSUE TITLE
Module #3 - Data management planning

### ISSUE THREAD

**Issue by amandawhitmire** [DataONEorg/dataone_lessons#16]
I am working on converting the Module 3 PPTX to an md file

**Comment by amandawhitmire** [comment]
@amandawhitmire is currently working on this lesson.

- [ ]  Transfer all text content to the slides
- [ ]  Compare text transferred to most recent ppt - ensure it's current
- [ ]  Re-export images - rework images to ensure high quality graphics in the presentation
- [ ]  Check notes - ensure all notes that aren't a duplicate of the slide content are transferred.

**Comment by amandawhitmire** [comment]
All content has been checked and updated, but I still having issues related to line spacing on the bullets. I suggest we go 1.15 or 1.5 spacing on those.

**Comment by aebudden** [comment]
All slides have been reviewed / edited / cleaned.  There are a few minor items remaining but I will migrate into a single issues thread.
