### ISSUE TITLE
Module #1 - Intro to Data Management

### ISSUE THREAD

**Issue by lwasser** [DataONEorg/dataone_lessons#17]
@lwasser is currently working on this lesson. 
- [x] Transfer all text content to the slides
- [x] Compare text transferred to most recent ppt - ensure it's current
- [x] Re-export images - rework images to ensure high quality graphics in the presentation
- [x] Check notes - ensure all notes that aren't a duplicate of the slide content are transferred.

**Comment by lwasser** [comment]
@jduckles - is it easy for you to run the image export code on module 1? I can't remember how to do it unfortunately

**Comment by lwasser** [comment]
@aebudden -- here is a slide that has too many words on it in my opinion

* https://dataoneorg.github.io/dataone_lessons/lessons/01_management/index.html#16

how do you suggest we deal with this? is this something you can look at?

**Comment by jduckles** [comment]
This is the tool I used: https://github.com/revan/pptx2md 

I think I ran it already on Module 1. These are the files that came out: https://github.com/DataONEorg/dataone_lessons/tree/master/lessons/01_management/images

**Comment by jduckles** [comment]
Or did you do those manually?

**Comment by lwasser** [comment]
hey @jduckles i did those manually. i need to redo them !

**Comment by lwasser** [comment]
So -- i see the code. thank you! how do you actually run that? do you create a file with that code in it and execute it at the command line?

**Comment by jduckles** [comment]
Ok, on a Mac you have to explicitly use `gsort` (available from homebrew by `brew install coreutils`), as BSD sort and GNU sort are slightly different in the flags they use, so my fork of `pptx2md` has an extra commit to the script which does that: https://github.com/jduckles/pptx2md/commit/9bef8440b7598b9709fa5dba499387a51dd52cf4

Then you just run:
```
./pptx2md L01_DataManagement_20160922.ppt
```

I've gone ahead and done this for you and the output [is here (zipfile)](https://jduckles-dropshare.s3-us-west-2.amazonaws.com/Lesson01-yNHccGUf4N.zip). Sorry I can't get it into a PR right now.

**Comment by lwasser** [comment]
Thank you @jduckles -- i'll help heather out with this issue now that i see how to do it.

https://github.com/DataONEorg/dataone_lessons/issues/69

I'll also document the workflow just for future as I can't seem to remember it to save my life! :)
I appreciate the help!!

**Comment by lwasser** [comment]
Closing this issue as all tasks are complete. Opened a new issue to begin the review process for this presentation.
