### ISSUE TITLE
Move images from pptx

### ISSUE THREAD

**Issue by jduckles** [DataONEorg/dataone_lessons#21]
Just keeping track of image extractions from PPTX files:

* [x] Lesson 1 
* [x] Lesson 2
* [x] Lesson 3
* [x] Lesson 4
* [x] Lesson 5
* [x] Lesson 6
* [x] Lesson 7
* [x] Lesson 8
* [x] Lesson 9
* [x] Lesson 10

**Comment by jduckles** [comment]
We're using this utility to remove the files: https://github.com/revan/pptx2md To run it on a non GNU unix system you'll need to replace the call for `sort` with `gsort`. On a mac you can get `gsort` by running `brew install coreutils`, assuming you have homebrew installed already.

**Comment by dbloom** [comment]
Awesome @jduckles  Works well.

**Comment by lwasser** [comment]
+1 +1 +1 !!!

**Comment by jduckles** [comment]
Final round of images came in with #43
