### ISSUE TITLE
Image size - bleeds onto the bottom footer logo

### ISSUE THREAD

**Issue by lwasser** [DataONEorg/dataone_lessons#22]
Is there a way to constrain the height of an image with our current structure? I was experimenting with min-height in the css but you can still notice that on some slides, there are images that bleed off the slide.
Here is one example:
https://dataoneorg.github.io/dataone_lessons/lessons/01_management/#16

**Comment by lwasser** [comment]
I've accommodated this in a few ways
one - is you use .wCaption[] it will resize the image to 70% width. 
Or place the image in a column - the only issue is it isn't centered that way.

**Comment by aebudden** [comment]
Resolved in the css
