### ISSUE TITLE
CCS Enhancement - Deactivate hyperlinking in photo attributions.

### ISSUE THREAD

**Issue by dbloom** [DataONEorg/dataone_lessons#24]
In Module 10 (Legal and Policy) all of the images are paired with photo attributions.  @lwasser has implemented a CSS enhancement to make the text attributions a gray color, but when the attribution is a URL it is automatically converted to a hyperlink, complete with blue color and underline.

Would be great to block the creation of the hyperlink and it's attributes.

**Comment by dbloom** [comment]
Added request to make the font size smaller than that standard text in the CSS.

**Comment by aebudden** [comment]
All slides have been reviewed / edited / cleaned.  There are a few minor items remaining but the css has been cleaned and these are largely resolved.
