### ISSUE TITLE
CSS Enhancement - Citation attribution in text

### ISSUE THREAD

**Issue by dbloom** [DataONEorg/dataone_lessons#26]
Also in Module 10, there are several slides (e.g., 3, 4) in which text needs an attribution.  It would awesome possum if that text could match the font size and color of the photo attributions noted in #24

**Comment by lwasser** [comment]
@dbloom is this the page you are referencing?

https://dataoneorg.github.io/dataone_lessons/lessons/10_policy/index.html#2

**Comment by aebudden** [comment]
All slides have been reviewed / edited / cleaned.  There are a few minor items remaining but the css is largely done and this issue resolved.
