### ISSUE TITLE
Please make sure .md files TITLE is in quotes

### ISSUE THREAD

**Issue by lwasser** [DataONEorg/dataone_lessons#31]
```
---
title: "Protecting Your Data: Backups, Archives, & Data Preservation"
---
```

if it is not in quotes you can run into issues with things not rendering.

**Comment by tpoisot** [comment]
Good call. This happens if you have : in your title because it's read as a key-value delimiter in yaml.

**Comment by hsoyka** [comment]
Is this best practice for titles in general? If so, we should update lesson 00 slide title to reflect the quotation marks for reference going forward.

**Comment by lwasser** [comment]
@hsoyka yes. We should just ensure titles in all YAML headers are in quotes. Module 6 wasn't rendering because of a character in the title. There are a few quirks associated with YAML Headers and the page not rendering and that is one of them :)
