### ISSUE TITLE
Module # 4- Data Entry and Manipulation

### ISSUE THREAD

**Issue by hsoyka** [DataONEorg/dataone_lessons#38]
@hsoyka is currently working on this lesson.
- [x]     Transfer all text content to the slides
- [x]     Compare text transferred to most recent ppt - ensure it's current
- [x]     Re-export images - rework images to ensure high quality graphics in the presentation
- [x]     Check notes - ensure all notes that aren't a duplicate of the slide content are transferred.
- [x]      Review edits and changes to final slides, read for clarity/images positioned properly.

**Comment by hsoyka** [comment]
Needs image updates.

**Comment by aebudden** [comment]
All slides have been reviewed / edited / cleaned.  There are a few minor items remaining but I will migrate into a single issues thread.
