### ISSUE TITLE
Module #5 - QA/QC

### ISSUE THREAD

**Issue by dbloom** [DataONEorg/dataone_lessons#53]
I have begun the process of moving this Module #5 into dataone_lessons. If anyone decided to add to this module, please let me know first.
- [x] Transfer all text content to the slides
- [x] Compare text transferred to most recent ppt - ensure it's current
- [x] Re-export images - rework images to ensure high quality graphics in the presentation
- [x] Check notes - ensure all notes that aren't a duplicate of the slide content are transferred.
- [ ] Update styling (Columns, image sizes, font size and color, etc.)

**Comment by dbloom** [comment]
All content is now in GitHub.  There is still a need for styling.

**Comment by aebudden** [comment]
All slides have been reviewed / edited / cleaned.  There are a few minor items remaining but I will migrate into a single issues thread.
