### ISSUE TITLE
Module #7 - Metadata

### ISSUE THREAD

**Issue by dbloom** [DataONEorg/dataone_lessons#64]
I have begun the process of moving this module into dataone_lessons. If anyone decided to add to this module, please let me know first.
- [ ] Transfer all text content to the slides
- [ ] Compare text transferred to most recent ppt - ensure it's current
- [ ]  Re-export images - rework images to ensure high quality graphics in the presentation
- [ ] Check notes - ensure all notes that aren't a duplicate of the slide content are transferred.
- [ ] Update styling (Columns, image sizes, font size and color, etc.)

**Comment by dbloom** [comment]
@jduckles Beginning work on Module 7 and when previewing the images, it looks like many failed to  render ("Diff not rendered.").  When you have a moment can you check to see if a second attempt might be more successful?  If not, let me know and I'll do it the old fashioned way.

https://github.com/DataONEorg/dataone_lessons/commit/29e139c839e4630e2557fc922daef656568b686b

**Comment by jduckles** [comment]
If you click VIEW they all render. Am I missing something?

**Comment by dbloom** [comment]
I suppose not.  Didn't realize that rendering on https://github.com/dbloom/dataone_lessons/commit/29e139c839e4630e2557fc922daef656568b686b was separate from the rendering when clicking the View button.  Just adds busy work in a big way which makes me feel https://github.com/dbloom/dataone_lessons/blob/29e139c839e4630e2557fc922daef656568b686b/lessons/06_protect/images/image12.jpeg.  I'll deal.  Thanks for checking.

**Comment by jduckles** [comment]
I'm not sure what is keeping them from showing up, but I share your rage.

![RAGE](https://media.giphy.com/media/p8Uw3hzdAE2dO/giphy.gif)

**Comment by amandawhitmire** [comment]
I am now working on this module as part of the CEOWG meeting.

**Comment by amandawhitmire** [comment]
This module is mostly complete for content and image placement/sizing. Will review one more time and then call it good.

**Comment by aebudden** [comment]
All slides have been reviewed / edited / cleaned.  There are a few minor items remaining but I will migrate into a single issues thread.
