### ISSUE TITLE
Module #9- images

### ISSUE THREAD

**Issue by hsoyka** [DataONEorg/dataone_lessons#69]
Images for Module #9 (Analysis) are missing/incorrect. The ones in the folder are the images for Module #8- Data citation. Folder for module #10 has correct images for module #10. 

I'm guessing that this was mixed up due to the renumbering of the modules. @jduckles would it be possible for you to easily pull these again using whatever magical process you executed in September at Tamaya? 

If not, no problem- I can go through manually and add them to the folder.

**Comment by lwasser** [comment]
hey @hsoyka  - @jduckles helped me out with my images  -and i can help in return given he invested that time for me! BUT i'm profoundly confused with respect to which ppt i should be using

https://drive.google.com/drive/u/0/folders/0B9b1IjMCv2pdWGdSMkRlZUl3RFE

There are 2 files in this folder now with different numbers. i don't know which presentation to use to extract images. #9 or #10 ? Please clarify

leah

**Comment by hsoyka** [comment]
Thanks for the help, @lwasser ! I've now deleted the old presentation from that folder-- you should only see one now (the correct one).

**Comment by lwasser** [comment]
ok great! i'll have a look. thanks @hsoyka i'm reviewing module 1 to ensure it's correct and will get to this next :)

**Comment by lwasser** [comment]
Ok @hsoyka -- i have added the images for lesson 09 to my current pull request. 

When you merge, they should be there and you can reorganize as you need to. I created a new folder - L09-pptimages just so you didn't lose anything you may or may not need in the images folder. re-organize as you see fit!
https://github.com/DataONEorg/dataone_lessons/pull/73/commits

Leah

**Comment by lwasser** [comment]
@hsoyka can we close this issue now? i think it's resolved?
