### ISSUE TITLE
Lesson 01 - Feedback Needed on slide layout

### ISSUE THREAD

**Issue by lwasser** [DataONEorg/dataone_lessons#72]
NOTE: Moving this from an issue below to allow for focused discussion. 

@aebudden  & @hsoyka -- 
I am fairly happy with the L01 presentation at this point. In general, i think it would be good to go through the text and edit. There are a LOT of words, and things could be cut while retaining the same meaning. Further, i think in spots, the notes are more useful on the slide rather than in the notes. It's worth thinking about how these will be used and what message the graphics are supports to provide. If the graphics don't contribute to a message, I suggest we change them. 

## Slides with too many words:
Please review and edit the text!  

* https://dataoneorg.github.io/dataone_lessons/lessons/01_management/index.html#17
* https://dataoneorg.github.io/dataone_lessons/lessons/01_management/index.html#23

## Another text loaded slide with a random image
Please review
* https://dataoneorg.github.io/dataone_lessons/lessons/01_management/index.html#16

## NEED REVIEW
the slides below need review. the original was very dense with text and also had a random image at the bottom. 
Please determine what content should remain on these slides and edit as you see fit. 

* https://dataoneorg.github.io/dataone_lessons/lessons/01_management/index.html#11 (thru 13)

* https://dataoneorg.github.io/dataone_lessons/lessons/01_management/index.html#19 -- I edited the text on this slide to be less verbose and informal. please review.

** slides 20-21 - i divided into two slides. We could adjust styles to fit text but it's a lot of text. 
* slides 28-9 - i broke these up into two slides - once again a lot of text. 
* slides 30-32 -- a LOT of text and a random very small graphic that could be cool if things were laid out better. Please have a look. 
* slide 38 - the CCBYO graphic is a bit large - we may need to either resize it OR create a style for a small graphic. 

## Slides that need graphic work: 

* The slide below has a bunch of images on it - each with a citation. Someone needs to make a graphic for this and I suggest we remove some of the images as they really aren't all necessary. 
https://dataoneorg.github.io/dataone_lessons/lessons/01_management/index.html#7

* The slide below has text in the notes but the slide really isn't at all self explanatory. I added it to the slide. But also it hink the graphic needs some work. Please have a look.
https://dataoneorg.github.io/dataone_lessons/lessons/01_management/index.html#8

* https://dataoneorg.github.io/dataone_lessons/lessons/01_management/index.html#24 - this slide has a collage of images with some text. i'm not exactly sure what the graphic shows (maybe it's trying to get at assimilation?) but it should be revisited.

**Comment by hsoyka** [comment]
Hi Leah, I think you're right that the slides likely need to be edited. I think that most of the modules have at least some of the same concerns (too much extraneous text, images that don't pertain to text, notes that are more useful as slides); obviously a lot is subjective. All three of the modules that I'm working on have at least a few areas where I have already made cuts and changes for the sake of clarity. I think others in the WG have been doing the same with their modules.
Do you think that you can make some of these changes for module 1? I'd be happy to talk with you about any that you don't feel comfortable making without discussion.

**Comment by hsoyka** [comment]
Also- not sure what to call this? The title for this module needs to be updated (remove the "Lesson 1") so that it matches the formatting of the others here: https://dataoneorg.github.io/dataone_lessons/

**Comment by lwasser** [comment]
hey @hsoyka I'm not sure comfortable making the text edits as i didn't make the original presentation and I really don't understand why there are such large chunks of text. For the slides at the top - they are long quotes - almost use cases or examples. I wouldn't have something like this in a powerpoint presentation, probably ever. But I also may be missing something important. I think someone from DataOne should step in and provide guidance. I am happy to help implement given some feedback. thank you.

**Comment by aebudden** [comment]
All slides have been reviewed / edited / cleaned.  There are a few minor items remaining but I will migrate into a single issues thread.
