### ISSUE TITLE
Module #9- Data Analysis and Workflows

### ISSUE THREAD

**Issue by hsoyka** [DataONEorg/dataone_lessons#75]
@hsoyka is currently working on this lesson. 
- [x]     Transfer all text content to the slides
- [x]     Compare text transferred to most recent ppt - ensure it's current
- [x]     Re-export images - rework images to ensure high quality graphics in the presentation
- [x]     Check notes - ensure all notes that aren't a duplicate of the slide content are transferred.
- [ ]      Review edits and changes to final slides, read for clarity/images positioned properly.

I'm still working on this lesson-- please get in touch with me before you make any changes/updates!

**Comment by hsoyka** [comment]
Check images and final citation slide before completion.

**Comment by aebudden** [comment]
All slides have been reviewed / edited / cleaned.  There are a few minor items remaining but I will migrate into a single issues thread.
