### ISSUE TITLE
Module #2- Data Sharing

### ISSUE THREAD

**Issue by hsoyka** [DataONEorg/dataone_lessons#76]
- [x]     Transfer all text content to the slides
- [ ]     Compare text transferred to most recent ppt - ensure it's current
- [x]     Re-export images - rework images to ensure high quality graphics in the presentation
- [ ]     Check notes - ensure all notes that aren't a duplicate of the slide content are transferred.
- [ ]      Review edits and changes to final slides, read for clarity/images positioned properly.

**Comment by aebudden** [comment]
Title and subtitle fonts are not sized hierarchically. CSS issue?
Lesson topics slide missing.
Lots of text running over into footer logo.  Some could be resolved through CSS of bullet spacing.
Space between title and paragraph text varies on multiple slides.

**Comment by aebudden** [comment]
All slides have been reviewed / edited / cleaned.  There are a few minor items remaining but I will migrate into a single issues thread.
