### ISSUE TITLE
The Layout Issues Thread

### ISSUE THREAD

**Issue by hsoyka** [DataONEorg/dataone_lessons#80]
Put your concerns about slide layout (across all modules) here!

You can also link to other module-specific issues in your post to make them easier to find.

**Comment by hsoyka** [comment]
Can we create a standardized template for the last page (citation/cc-by) so that all ten modules have the same one?

**Comment by hsoyka** [comment]
Common issue that I am seeing is that text is cutting into/being cut off by the DataONE logo in the lower left corner. Should we consider moving the logo to the top of the slides in order to accommodate this? (FWIW, I tend to think audiences might be more likely be able to see it in a presentation if its in the top 2/3 of the screen, but that could just be personal preference.)

**Comment by hsoyka** [comment]
Spacing issue for bullets- @amandawhitmire raised this in the issue for Module 3. Can we change this to 1.15 or 1.5?

**Comment by aebudden** [comment]
css largely done.  these issues resolved.
